before_script:
  - git lfs pull


stages:
  - test
  - deploy
  - cleanup


test_{{ cookiecutter.project_slug }}:
  stage: test
  script:
    - source /root/mambaforge/bin/activate ci_env

    # install missing dependencies on the CI container
    - mamba env update --name ci_env --file tests/CI_docker/context/environment_{{ cookiecutter.project_slug }}.yml  --prune

    # run tests
    - make pytest

    # create the docs
    - make docs

  artifacts:
    expose_as: 'Test and coverage report'
    paths:
    - htmlcov/
    - report.html
    - docs/_build/html/
    reports:
      cobertura: coverage.xml
      junit: report.xml
    expire_in: 30 days
    when: always


test_styles:
  stage: test
  script:
    - source /root/mambaforge/bin/activate ci_env
    - make lint
  artifacts:
    paths:
    - tests/linting/flake8.log
    - tests/linting/pycodestyle.log
    - tests/linting/pydocstyle.log
    when: always


test_urls:
  stage: test
  script:
    - source /root/mambaforge/bin/activate ci_env
    - pip install -U urlchecker
    - make urlcheck
  when: always


test_{{ cookiecutter.project_slug }}_install:
  stage: test
  script:
    - source /root/mambaforge/bin/activate

    # update base environment
    - conda update -n base -c conda-forge --all

    # create {{ cookiecutter.project_slug }} environment from environment_{{ cookiecutter.project_slug }}.yml
    - mamba env create --name {{ cookiecutter.project_slug }}_testinstall -f tests/CI_docker/context/environment_{{ cookiecutter.project_slug }}.yml
    - conda activate {{ cookiecutter.project_slug }}_testinstall

    # run installer
    - pip install .

    # check if all dependencies are correctly installed
    - pip check

    # test if its importable
    - cd ..
    - ls
    - python -c "import {{ cookiecutter.project_slug }}; print({{ cookiecutter.project_slug }})"
  only:
    - main


pages:  # this job must be called 'pages' to advise GitLab to upload content to GitLab Pages
  stage: deploy
  dependencies:
    - test_{{ cookiecutter.project_slug }}
  script:
    # Create the public directory
    - rm -rf public
    - mkdir public
    - mkdir -p public/doc
    - mkdir -p public/images/
    - mkdir -p public/coverage
    - mkdir -p public/test_reports

    # Copy over the docs
    - cp -r docs/_build/html/* public/doc/
    # - cp -r docs/images/* public/images/  # we don't have images so far

    # Copy over the coverage reports
    - cp -r htmlcov/* public/coverage/

    # Copy over the test reports
    - cp report.html public/test_reports/

    # Check if everything is working great
    - ls -al public
    - ls -al public/doc
    - ls -al public/coverage
    - ls -al public/test_reports
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - main
