version: "3.3"

services:
    fastapi_boilerplate:
        image: ${API_IMAGE_NAME}:${VERSION}
        container_name: ${API_CONTAINER_NAME}
        build: .
        command: bash -c "mamba run --no-capture-output -n fastapi_boilerplate python run.py"
        network_mode: host
        restart: always
        environment:
            - API_SERVER_SCOPE=${API_SERVER_SCOPE}
            - PORT=${PORT}
            - DATA_DIR_IN=/home/data/data_dir
            - DATA_DIR=${DATA_DIR}
        volumes:
            - ${DATA_DIR}:/home/data/data_dir
